Release "app" has been upgraded. Happy Helming!
NAME: app
LAST DEPLOYED: Fri Apr 14 02:35:01 2023
NAMESPACE: otus-hw3
STATUS: pending-upgrade
REVISION: 30
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: otus-helm-hw3/templates/db-sercret.yaml
apiVersion : v1
kind : Secret
metadata:
  name : db-secrets
stringData:
  username : root
  password : root
---
# Source: otus-helm-hw3/templates/db-config.yaml
apiVersion : v1
kind : ConfigMap
metadata:
  name : db-config
data:
  host : postgres-postgresql
  dbName: postgres
  port: '5432'
---
# Source: otus-helm-hw3/templates/app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: otus-hw3
  labels:
    name: app-service
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
      name: http
---
# Source: otus-helm-hw3/templates/app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-hw-3-deploy
  namespace: otus-hw3
  labels:
    date: "1681428901"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: andrewotuscourse/hw3-app:latest
          resources:
            limits:
              memory: "256Mi"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbName

            - name: DB_PORT  # Setting Database port from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: port

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password

