app:
  namespace: otus-hw3
  service:
    name: app-service
    type: ClusterIP
    port: 80
  deploy:
    appName: app
    deployName: otus-hw-3-deploy
    replicaCount: 2
    appPort: 8000
    image:
      repository: andrewotuscourse
      name: hw3-app
      pullPolicy: Always
      tag: ":latest"
