apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-monitor
  labels:
    app: metrics-monitor
  namespace: otus-hw4
    
spec:
  endpoints:
    - port: http-traffic
      scrapeTimeout: 30s
      path: /actuator/prometheus
      honorLabels: true
      scheme: http
  namespaceSelector:
    matchNames:
      - default
      - otus-hw4
  selector:
    matchLabels:
      app: app
