apiVersion: v2
name: otus-helm-hw4
description: A Helm chart is OTUS homework №4

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: ingress-nginx
    version: 4.6.0
    repository: https://kubernetes.github.io/ingress-nginx
