apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-monitor
  labels:
    app: metrics-monitor
  namespace: {{ .Values.app.namespace }}
    
spec:
  endpoints:
    - port: http-traffic
      scrapeTimeout: 10s
      path: "/actuator/prometheus"
      honorLabels: true
      scheme: http
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: {{ .Values.app.deploy.appName }}
      operated-prometheus: "true"
