apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.deploy.appName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.deploy.appName }}
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
      name: http-traffic
